### ISSUE TITLE
Add a timeout option to the requests

### ISSUE THREAD

**Issue by rkhwaja** [tapanpandita/pocket#17]
Or expose the request in some way so that the client can set the timeout themselves

**Comment by tapanpandita** [comment]
@rkhwaja Thanks for pointing this out. Will only be able to get to changes in a couple of weeks. Happy to accept a PR.

**Comment by rkhwaja** [comment]
I solved it by overriding _post_request:

class PocketWithTimeout(Pocket):
	@staticmethod
	def _post_request(url, payload, headers):
		return post(url, data=payload, headers=headers, timeout=60)
